import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
let chromium;try{({chromium}=await import('playwright'))}catch{({chromium}=await import(pathToFileURL('C:/Users/QDU/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs')))}

async function setting(key){const map={readingFont:'writing',uiFont:'writing',fontWeight:'writing',readingWidth:'writing',readingLineHeight:'writing',density:'layout',corners:'layout',sidebarTone:'layout',sidebarSide:'layout',navigationStyle:'layout',defaultMode:'layout',showWeek:'today',showOnThisDay:'today',showEmotionHelper:'today',showDailyModes:'today',reduceMotion:'accessibility'};const category=map[key]||(['data','privacy','accessibility'].includes(key)?key:'appearance');const select=page.locator('.settings-mobile-select');if(await select.isVisible())await select.selectOption(category);else await page.locator(`[data-category="${category}"]`).click()}
const browser=await chromium.launch({headless:true,channel:'msedge'});
// launch creates a temporary test profile; never connect to a user browser/profile.
const TEST_URL='http://127.0.0.1:4174';
assert.notEqual(TEST_URL,'http://127.0.0.1:4173');
const context=await browser.newContext({acceptDownloads:true});
const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
page.on('dialog',d=>d.accept());
const click=async action=>{await page.waitForFunction(()=>document.querySelector('#app').getAttribute('aria-busy')!=='true');await page.locator(`[data-action="${action}"]`).first().click();await page.waitForFunction(()=>document.querySelector('#app').getAttribute('aria-busy')!=='true')};
const saveIdle=()=>page.waitForFunction(()=>document.querySelector('#save-state').textContent==='محفوظ على جهازك');
await mkdir('tests/artifacts',{recursive:true});
try{
await page.goto(TEST_URL);await page.locator('[data-action="finish-onboarding"]').waitFor();await page.screenshot({path:'tests/artifacts/onboarding.png',fullPage:true});
await click('finish-onboarding');await page.locator('[name="answer"]').fill('رحت ويا صديقي نشتري حذاء');await click('next-question');await page.locator('[name="answer"]').fill('تضايقت، وبعدها ارتحت');await click('next-question');await page.locator('[name="answer"]').fill('ضحكنا على البحث عن المقاس');await saveIdle();await page.reload();await page.locator('[data-action="start"]').waitFor();await click('start');assert.equal(await page.locator('[name="answer"]').inputValue(),'ضحكنا على البحث عن المقاس');await click('next-question');await page.locator('[name="entry"]').waitFor();assert.match(await page.locator('[name="entry"]').inputValue(),/رحت ويا صديقي نشتري حذاء/);await click('complete');await page.locator('[data-action="history"]').waitFor();console.log('PASS quick interview, autosave recovery, composition, completion');
await page.locator('[data-nav="today"]').first().click();await page.screenshot({path:'tests/artifacts/today-desktop.png',fullPage:true});await click('capture');await page.locator('[name="capture-content"]').fill('القهوة ويا علي');await click('save-capture');await page.getByText('القهوة ويا علي',{exact:true}).waitFor();await page.reload();await page.getByText('القهوة ويا علي',{exact:true}).waitFor();console.log('PASS capture persists after reload');
await click('convert-capture');await page.getByRole('heading',{name:'أعد بناء يومي'}).waitFor();await click('edit-event');await page.locator('[name="title"]').fill('استراحة قهوة');await page.locator('[name="place"]').fill('البيت');await page.locator('[name="people"]').fill('علي، أحمد');await page.locator('[name="tags"]').fill('مضحك، إنجاز');await click('save-event');await click('companion');await page.locator('[name="answer"]').fill('الفنجان كان صغيرًا');await click('next-question');await page.locator('[name="answer"]').fill('احتجت استراحة');await click('next-question');await click('wizard-emotion');await click('uncertain-emotion');await page.locator('[data-action="uncertain-choice"][data-value="مختلط"]').click();await page.locator('[data-action="uncertain-choice"][data-value="قليلة"]').click();await page.locator('[data-action="uncertain-choice"][data-value="مو متأكد"]').first().click();await page.locator('[data-action="uncertain-choice"][data-value="صار شيء حلو بعد انتظار"]').click();await page.locator('[data-action="choose-emotion"][data-word="Relieved"]').click();await page.locator('[data-action="choose-emotion"][data-word="Joyful"]').click();await page.locator('[data-emotion-intensity]').first().fill('4');await page.locator('.emotion-word').filter({has:page.locator('[data-word="Relieved"]')}).locator('summary').click();await page.locator('[data-action="save-word"][data-word="Relieved"]').click();await click('save-emotions');assert.match(await page.locator('[name="answer"]').inputValue(),/مرتاح بعد قلق \(4\/5\)/);await click('end-session');console.log('PASS day reconstruction, linked people/place, mixed emotions, vocabulary');
await page.locator('[data-nav="search"]').first().click();await page.locator('[name="query"]').fill('القهوة');await page.locator('.advanced-search summary').click();await page.locator('[name="person"]').fill('علي');await page.locator('#search-form button[type="submit"]').click();await page.locator('#search-results .entry-row').waitFor();console.log('PASS full-text search with person filter');
await page.locator('[data-nav="calendar"]').first().click();await page.locator('.calendar-day:not(.blank)').first().waitFor();assert.ok(await page.locator('.calendar-day:not(.blank)').count()>27);console.log('PASS calendar');
await page.locator('[data-nav="memories"]').first().click();await click('people');assert.equal(await page.getByRole('heading',{name:'علي',exact:true}).count(),1);await click('entity-events');await page.locator('#entity-results .timeline-event').waitFor();console.log('PASS people entity retrieval');
await page.locator('[data-nav="settings"]').first().click();await setting('theme');await page.locator('[data-pref="theme"]').selectOption('dark');await setting('textSize');await page.locator('[data-pref="textSize"]').selectOption('22');await page.setViewportSize({width:375,height:812});await page.locator('[data-nav="today"]').last().click();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'tests/artifacts/today-mobile-dark.png',fullPage:true});await page.setViewportSize({width:1440,height:1000});await page.locator('[data-nav="settings"]').first().click();await setting('theme');await page.locator('[data-pref="theme"]').selectOption('light');await setting('textSize');await page.locator('[data-pref="textSize"]').selectOption('17');console.log('PASS responsive, dark theme, adjustable text');
// Browser-level IndexedDB and backup transaction tests use an isolated origin/context below.
const integrity=await context.newPage();await integrity.goto(TEST_URL);await integrity.waitForFunction(()=>document.querySelector('.shell'));
const checks=await integrity.evaluate(async()=>{const {JournalDB,newDay}=await import('./core.js');if(location.port!=='4174')throw Error('Not isolated test origin');const db=await new JournalDB('qadawi-test-integrity').open();const d=newDay('2026-10-02');d.entryContent='القهوة، تفصيل اختباري';await db.put(d);const before=await db.backup();await db.setProtection('test phrase longer than ten');const raw=await db.allRaw();if(raw.some(r=>JSON.stringify(r.payload).includes('القهوة')))throw Error('Encryption leaked content');const encrypted=await db.backup();if(encrypted.format!=='qadawi-journal-encrypted')throw Error('Unencrypted backup');db.lock();let rejected=false;try{await db.get(d.id)}catch{rejected=true}if(!rejected)throw Error('Lock allowed content read');try{await db.unlock('wrong')}catch{}if(!db.locked)throw Error('Wrong key unlocked');await db.unlock('test phrase longer than ten');await db.setProtection(null);const after=await db.backup();if(JSON.stringify(after.records)!==JSON.stringify(before.records))throw Error('Encryption roundtrip altered data');const count=await db.count('day');try{await db.restore({format:'qadawi-journal',schemaVersion:1,records:[{id:'broken',kind:'day'}]})}catch{}if(await db.count('day')!==count)throw Error('Invalid import mutated data');await db.clear();await db.restore(before);if(await db.count('day')!==count)throw Error('Restore lost entries');return {records:before.records.length,encrypted:true,restored:true}});console.log('PASS IndexedDB encryption, wrong key, validated backup roundtrip',checks);await integrity.close();
await page.reload();await page.locator('.shell').waitFor();await page.locator('[data-nav="journal"]').first().click();await click('open-day');await click('delete-day');await page.locator('[data-nav="settings"]').first().click();await setting('data');await click('trash');await click('restore-trash');await page.locator('[data-nav="journal"]').first().click();await page.locator('.entry-row').waitFor();console.log('PASS trash cascade and restoration');
await page.reload();await page.waitForFunction(()=>navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();await page.locator('.shell').waitFor();await click('capture');await page.locator('[name="capture-content"]').fill('لقطة محفوظة بدون اتصال');await click('save-capture');await context.setOffline(false);console.log('PASS offline shell and offline capture');
assert.deepEqual(errors,[]);await writeFile('tests/artifacts/results.json',JSON.stringify({passed:true,checks,errors},null,2));console.log('ALL BROWSER CHECKS PASSED');
}catch(e){console.log('BROWSER ERRORS',errors);console.log('TOAST',await page.locator('#toast').textContent());await page.screenshot({path:'tests/artifacts/failure.png',fullPage:true});throw e}finally{await browser.close()}
