import test from 'node:test';
import assert from 'node:assert/strict';
import {compose,newDay,normalize,esc,validateBackup,deriveKey,encrypt,decrypt,matchesSearch} from '../dist/core.js';
test('Composition contains only supplied facts; empty sections are absent',()=>{const d=newDay('2026-10-02');d.rawResponses=[{category:'event',answer:'رحت ويا صديقي نشتري حذاء',label:'ما حدث'},{category:'emotion',answer:'تضايقت',label:'شعوري'}];const output=compose(d);assert.match(output,/رحت ويا صديقي نشتري حذاء/);assert.match(output,/تضايقت/);assert.doesNotMatch(output,/مطعم|سعيد|ضحك|Tomorrow|باجر/)});
test('Event time uncertainty is preserved',()=>{const output=compose(newDay('2026-10-02'),[{description:'اشتريت كتابًا',approximateStartTime:'18:00',timeConfidence:'approximate'}]);assert.match(output,/تقريبًا 18:00/)});
test('Output escapes stored HTML and attribute injection',()=>{assert.equal(esc('<img src=x onerror="alert(1)">'), '&lt;img src=x onerror=&quot;alert(1)&quot;&gt;');assert.equal(esc("'"),'&#39;')});
test('Arabic normalization and full content phrase search',()=>{assert.equal(normalize('أَحْمَد'),normalize('احمد'));const r={date:'2026-10-02',entryContent:'رحت إلى الجامعة ويا أحمد',tags:['دراسة']};assert.equal(matchesSearch(r,{query:'الجامعة ويا احمد',from:'2026-10-01',to:'2026-10-02'}),true);assert.equal(matchesSearch(r,{query:'مقهى'}),false)});
test('Backup schema rejects invalid formats, duplicate IDs, and unsafe media before writes',()=>{const d=newDay('2026-10-02'),b={format:'qadawi-journal',schemaVersion:1,records:[d]};assert.equal(validateBackup(b),b);assert.throws(()=>validateBackup({...b,schemaVersion:999}));assert.throws(()=>validateBackup({...b,records:[d,d]}));assert.throws(()=>validateBackup({...b,records:[{id:'x',kind:'media',mime:'image/svg+xml',data:'data:image/svg+xml;base64,eA=='}]}));assert.throws(()=>validateBackup(JSON.parse('{"format":"qadawi-journal","schemaVersion":1,"records":[{"id":"x","kind":"word","__proto__":{}}]}')))});
test('AES-GCM roundtrip, unique IVs, wrong-key and tamper rejection',async()=>{const salt=Buffer.from('1234567890abcdef').toString('base64');const key=await deriveKey('a long test passphrase',salt),wrong=await deriveKey('a different passphrase',salt);const input={text:'تفصيل خاص من يومي',media:'original bytes'};const a=await encrypt(input,key),b=await encrypt(input,key);assert.notEqual(a.iv,b.iv);assert.deepEqual(await decrypt(a,key),input);await assert.rejects(decrypt(a,wrong));const bytes=Buffer.from(a.cipher,'base64');bytes[2]^=1;await assert.rejects(decrypt({...a,cipher:bytes.toString('base64')},key))});
