import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
let chromium;try{({chromium}=await import('playwright'))}catch{({chromium}=await import(pathToFileURL('C:/Users/QDU/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs')))}

async function setting(key){const map={readingFont:'writing',uiFont:'writing',fontWeight:'writing',readingWidth:'writing',readingLineHeight:'writing',density:'layout',corners:'layout',sidebarTone:'layout',sidebarSide:'layout',navigationStyle:'layout',defaultMode:'layout',showWeek:'today',showOnThisDay:'today',showEmotionHelper:'today',showDailyModes:'today',reduceMotion:'accessibility'};const category=map[key]||(['data','privacy','accessibility'].includes(key)?key:'appearance');const select=page.locator('.settings-mobile-select');if(await select.isVisible())await select.selectOption(category);else await page.locator(`[data-category="${category}"]`).click()}
const browser=await chromium.launch({headless:true,channel:'msedge',args:['--use-fake-device-for-media-stream','--use-fake-ui-for-media-stream']});
const context=await browser.newContext({acceptDownloads:true,permissions:['microphone']});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.type()==='prompt'?d.accept('test secure phrase for backup'):d.accept());
const idle=()=>page.waitForFunction(()=>document.querySelector('#app').getAttribute('aria-busy')!=='true');
const click=async a=>{await idle();await page.locator(`[data-action="${a}"]`).first().click();await idle()};
const nav=async a=>{await idle();await page.locator(`[data-nav="${a}"]`).first().click();await idle()};
await mkdir('tests/artifacts',{recursive:true});
try{
await page.goto('http://127.0.0.1:4174');await click('finish-onboarding');await page.locator('[name="answer"]').fill('درست في البيت');await click('end-session');await click('complete');
await nav('today');await click('capture');await page.locator('[name="capture-content"]').fill('صورة للاختبار فقط');
const png=await page.evaluate(async()=>{const canvas=document.createElement('canvas');canvas.width=8;canvas.height=8;canvas.getContext('2d').fillRect(0,0,8,8);return canvas.toDataURL('image/png').split(',')[1]});
const choose=page.waitForEvent('filechooser');await click('attach');await (await choose).setFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.locator('#dialog-media img').waitFor();await page.locator('#dialog-media .media-preview').click();await page.locator('.image-viewer[open]').waitFor();await page.keyboard.press('Escape');await page.locator('.image-viewer').waitFor({state:'detached'});assert.equal(await page.locator('.image-viewer').count(),0);assert.equal(await page.locator('#dialog[open]').count(),1);await click('record');await page.waitForTimeout(700);await click('record');await page.locator('#dialog-media audio').waitFor();await click('save-capture');console.log('PASS photo attachment and original voice recording');
await nav('settings');await setting('data');await click('backup');const dl=page.waitForEvent('download');await click('export-json');const backup=await dl;await backup.saveAs('tests/artifacts/backup-test.json');const data=JSON.parse(await readFile('tests/artifacts/backup-test.json','utf8'));assert.ok(data.records.some(r=>r.kind==='media'&&r.mime.startsWith('audio/')));assert.ok(data.records.some(r=>r.kind==='media'&&r.mime==='image/png'));await page.evaluate(async input=>{const {validateBackup}=await import('./core.js');validateBackup(input)},data);
const importer=page.waitForEvent('filechooser');await click('import-json');await (await importer).setFiles('tests/artifacts/backup-test.json');await click('confirm-import');await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('استعدنا النسخة'));console.log('PASS complete JSON backup with media and UI restore');
await nav('today');await click('free');await page.evaluate(async()=>{const {JournalDB}=await import('./core.js');const real=JournalDB.prototype.batch;let fail=true;JournalDB.prototype.batch=function(...args){if(fail){fail=false;return Promise.reject(new DOMException('Test quota failure','QuotaExceededError'))}return real.apply(this,args)}});await page.locator('[name="entry"]').fill('مسودة يجب أن تبقى عند فشل التخزين');await page.locator('#save-error').waitFor();assert.equal(await page.locator('[name="entry"]').inputValue(),'مسودة يجب أن تبقى عند فشل التخزين');await click('retry-save');await page.reload();await click('free');assert.equal(await page.locator('[name="entry"]').inputValue(),'مسودة يجب أن تبقى عند فشل التخزين');console.log('PASS failed-save retention and retry');
await page.locator('[name="entry"]').fill('<img src=x onerror="window.injection=1">\n## اختباري فقط');await click('complete');assert.equal(await page.evaluate(()=>window.injection),undefined);assert.ok((await page.locator('.reading').textContent()).includes('<img src=x'));console.log('PASS stored XSS payload renders as text');
await nav('memories');await click('new-collection');await page.locator('[name="collection-name"]').fill('مجموعة اختبار');await click('save-collection');await nav('journal');await click('open-day');await click('add-collection');await click('choose-collection');await nav('memories');await page.getByRole('button',{name:'مجموعة اختبار 1 يوم محفوظ'}).click();await page.locator('#collection-results .entry-row').waitFor();console.log('PASS custom collection');
await click('letters');await click('new-letter');await page.locator('[name="letter-content"]').fill('إلى نفسي — اختبار');await click('save-letter');await page.getByText('موعدها بعده ما وصل. إخفاؤها هنا تذكير فقط، وليس قفلًا حقيقيًا.').waitFor();await nav('memories');await click('snapshots');await click('new-snapshot');await page.locator('[name="snapshot-answer"]').fill('الدراسة');await click('snapshot-next');await page.locator('[name="snapshot-answer"]').fill('العائلة');await click('snapshot-save');await page.getByText('الدراسة',{exact:true}).waitFor();console.log('PASS future letters and life snapshot');
await nav('insights');await click('reviews');await page.locator('[name="review-reflection"]').fill('مراجعة أسبوع اختبار');await page.waitForFunction(()=>document.querySelector('#save-state').textContent==='محفوظ على جهازك');await nav('settings');await setting('privacy');await click('enable-lock');await page.locator('[name="new-passphrase"]').fill('test secure phrase for backup');await page.locator('[name="repeat-passphrase"]').fill('test secure phrase for backup');await page.locator('[name="understand-lock"]').check();await click('save-lock');await click('lock');await page.locator('[name="passphrase"]').fill('wrong');await page.locator('#unlock-form button').click();await page.getByText('لم تُفتح البيانات. تحقق من عبارة المرور.').waitFor();await page.locator('[name="passphrase"]').fill('test secure phrase for backup');await page.locator('#unlock-form button').click();await page.locator('.shell').waitFor();await nav('settings');await setting('data');await click('backup');const encdl=page.waitForEvent('download');await click('export-json');await (await encdl).saveAs('tests/artifacts/encrypted-test.json');assert.equal(JSON.parse(await readFile('tests/artifacts/encrypted-test.json','utf8')).format,'qadawi-journal-encrypted');const encryptedImporter=page.waitForEvent('filechooser');await click('import-json');await (await encryptedImporter).setFiles('tests/artifacts/encrypted-test.json');await click('confirm-import');await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('استعدنا النسخة'));console.log('PASS review autosave, UI lock/unlock, encrypted backup restore');
await nav('today');await page.locator('#toast').evaluate(e=>e.classList.remove('visible'));await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'tests/artifacts/final-desktop.png',fullPage:true});await nav('settings');await setting('theme');await page.locator('[data-pref="theme"]').selectOption('dark');await setting('textSize');await page.locator('[data-pref="textSize"]').selectOption('22');await nav('today');await page.setViewportSize({width:375,height:812});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'tests/artifacts/final-mobile.png',fullPage:true});
await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.evaluate(()=>matchMedia('(prefers-reduced-motion:reduce)').matches),true);const names=await page.locator('button').evaluateAll(buttons=>buttons.filter(b=>!b.textContent.trim()&&!b.getAttribute('aria-label')).length);assert.equal(names,0);console.log('PASS mobile enlarged text, reduced motion, control labels');
assert.deepEqual(errors,[]);await writeFile('tests/artifacts/features-results.json',JSON.stringify({passed:true,errors},null,2));console.log('ALL FEATURE CHECKS PASSED');
}catch(e){console.log('ERRORS',errors);console.log('TOAST',await page.locator('#toast').textContent());await page.screenshot({path:'tests/artifacts/features-failure.png',fullPage:true});throw e}finally{await browser.close()}
