import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import(pathToFileURL('C:/Users/QDU/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs'));
const phase=process.argv[2]||'matrix';
const browser=await chromium.launch({headless:true,channel:'msedge'});
const context=await browser.newContext({viewport:{width:390,height:844}});
const page=await context.newPage(),errors=[],failures=[],checks=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push('Console: '+m.text())});page.on('response',r=>{if(r.status()>=400)failures.push([r.status(),r.url()])});
const idle=()=>page.waitForFunction(()=>document.querySelector('#app')?.getAttribute('aria-busy')!=='true');
const click=async a=>{await idle();await page.locator(`[data-action=${a}]:visible`).first().click();await idle()};
const category=async id=>{if(await page.locator('.settings-mobile-select').isVisible())await page.locator('.settings-mobile-select').selectOption(id);else await page.locator(`[data-category=${id}]`).click()};
const nav=async r=>{await idle();if(r==='search')return click('search');if(r==='backup'){await nav('settings');await category('data');return click('backup')}await page.locator(`[data-nav=${r}]:visible`).first().click();await idle()};
const inspect=async label=>{await idle();await page.evaluate(()=>document.fonts.ready);const r=await page.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth,dir:document.documentElement.dir,unnamed:[...document.querySelectorAll('button')].filter(e=>e.checkVisibility()&&!e.textContent.trim()&&!e.getAttribute('aria-label')).length,inputs:[...document.querySelectorAll('input:not([type=radio]):not([type=checkbox]):not([type=range]):not([type=color]),textarea,select')].filter(e=>e.checkVisibility()).map(e=>({name:e.name||e.id,size:parseFloat(getComputedStyle(e).fontSize)})),dialog:document.querySelector('#dialog[open]')?.getBoundingClientRect().height||0}));assert.ok(r.scroll<=r.w,`${label} overflow ${r.scroll}/${r.w} ${r.scroll>r.w?JSON.stringify(await page.evaluate(()=>[...document.querySelectorAll('main *')].filter(e=>e.checkVisibility()&&e.getBoundingClientRect().width>innerWidth-36).slice(0,12).map(e=>({tag:e.tagName,classes:e.className,width:e.getBoundingClientRect().width,style:e.getAttribute('style'),wrap:getComputedStyle(e).flexWrap})))):''}`);assert.equal(r.dir,'rtl');assert.equal(r.unnamed,0,label);if(r.w<=700)assert.ok(r.inputs.every(e=>e.size>=16),`${label} inputs under 16px ${JSON.stringify(r.inputs)}`);if(r.dialog)assert.ok(r.dialog<=await page.evaluate(()=>innerHeight)+1,label+' tall dialog');checks.push({label,...r})};
const shot=async name=>{await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0);document.querySelector('#toast')?.classList.remove('visible')});await page.screenshot({path:`tests/artifacts/identity/${name}.png`,fullPage:true})};
async function mode(m){await nav('settings');await category('appearance');await page.locator('select[data-pref=theme]').selectOption(m);await page.waitForFunction(m=>document.documentElement.dataset.theme===m,m)}
async function views(prefix,screens=false){for(const r of ['today','journal','calendar','memories','insights','search','backup','settings']){await nav(r);await inspect(`${prefix}-${r}`);if(screens&&['today','calendar','settings','memories','backup','insights'].includes(r))await shot(`${prefix}-${r}`)}await nav('settings');await category('writing');await inspect(prefix+'-fonts');if(screens)await shot(prefix+'-fonts');await nav('today');await page.locator('[data-mode-new=quick]').click();await click('start');await inspect(prefix+'-guided');if(screens)await shot(prefix+'-guided');await nav('today');await page.locator('[data-mode-new=normal]').click();await click('start');await inspect(prefix+'-rebuild');if(screens)await shot(prefix+'-rebuild');await nav('today');await click('free');await inspect(prefix+'-free');if(screens)await shot(prefix+'-free');await click('reading');await inspect(prefix+'-reading');if(screens)await shot(prefix+'-reading');await click('capture');await inspect(prefix+'-capture');if(screens)await shot(prefix+'-capture');await click('close-dialog')}
try{
 await mkdir('tests/artifacts/identity',{recursive:true});await page.goto('http://127.0.0.1:4174');assert.equal(new URL(page.url()).port,'4174');await click('close-dialog');
 await page.evaluate(async()=>{const {JournalDB,newDay,dateKey}=await import('./core.js');const {defaultAppearance}=await import('./appearance.js');const db=await new JournalDB().open();const d=newDay(dateKey());d.title='صفحة اختبار معزولة — My memories';d.entryContent='## من يوم الاختبار\nتفصيل صغير أريد حفظه. My words ١٢٣ 123.\n\n> جملة للاختبار فقط.\n- تفصيل أول\n- تفصيل ثانٍ\n\n'+('هذه فقرة طويلة لاختبار القراءة فقط. Arabic and English, ١٢٣.\n\n'.repeat(15));d.status='draft';await db.put(d);const p=await db.get('settings:main')||{id:'settings:main',kind:'settings'};Object.assign(p,defaultAppearance(),{onboarded:true,theme:'light',fontSize:17});await db.put(p)});await page.reload();await idle();
 if(phase==='mobile'){for(const width of [360,390,430]){await page.setViewportSize({width,height:844});await views(`mobile-${width}`,width===390);const title=await page.locator('.reading>h1').evaluate(e=>parseFloat(getComputedStyle(e).fontSize));assert.ok(title<32);const body=await page.locator('.reading-section p').first().evaluate(e=>({size:parseFloat(getComputedStyle(e).fontSize),line:parseFloat(getComputedStyle(e).lineHeight)}));assert.ok(body.size>=18&&body.line>=body.size*1.6)}}
 if(phase==='navigation'){
  for(const route of ['today','journal','calendar','memories','search']){await nav(route);await inspect('navigation-'+route)}await nav('today');await click('capture');await page.locator('[name=capture-content]').fill('لقطة اختبار معزولة');await click('save-capture');await nav('today');await page.getByText('لقطة اختبار معزولة',{exact:true}).waitFor();await click('free');await click('focus-mode');await page.locator('[name=entry]').focus();await page.evaluate(()=>{Object.defineProperty(visualViewport,'height',{configurable:true,get:()=>420});visualViewport.dispatchEvent(new Event('resize'))});await page.waitForFunction(()=>document.body.dataset.keyboard==='true');assert.equal(await page.locator('.mobile-nav').isVisible(),false);assert.equal(await page.locator('.float-capture').isVisible(),false);assert.ok(await page.locator('#save-state').isVisible());assert.ok(await page.getByRole('button',{name:'العودة إلى الدفتر',exact:true}).isVisible());await page.evaluate(()=>{delete visualViewport.height;document.activeElement.blur();visualViewport.dispatchEvent(new Event('resize'))});await page.waitForFunction(()=>document.body.dataset.keyboard==='false');await page.keyboard.press('Escape');assert.ok(await page.locator('.mobile-nav').isVisible());const cdp=await context.newCDPSession(page);await cdp.send('Emulation.setEmulatedMedia',{features:[{name:'display-mode',value:'standalone'}]});const standalone=await page.evaluate(()=>matchMedia('(display-mode:standalone)').matches);checks.push({standaloneEmulation:standalone,installedDeviceTest:'not available in isolated headless Edge',syntheticKeyboardMetrics:true});await inspect('navigation-restored');await shot('mobile-navigation-restored');await page.waitForFunction(()=>navigator.serviceWorker.controller);assert.ok(await page.evaluate(()=>navigator.serviceWorker.ready));
 }
 if(phase==='dark'){await page.setViewportSize({width:1366,height:768});await mode('dark');await views('dark-desktop',true);await page.setViewportSize({width:390,height:844});await views('dark-mobile',true);await nav('settings');await category('appearance');const states=await page.evaluate(async()=>{const {contrast}=await import('./themes.js');const root=getComputedStyle(document.documentElement);const value=x=>root.getPropertyValue('--'+x).trim();return {text:contrast(value('ink'),value('paper')),placeholder:contrast(value('muted'),value('surface')),primary:contrast(value('green'),value('on-accent')),control:contrast(value('control-border'),value('surface'))}});assert.ok(states.text>=4.5&&states.placeholder>=4.5&&states.primary>=4.5&&states.control>=3);checks.push({darkContrast:states})}
 if(phase==='accessibility'){
  await page.setViewportSize({width:1366,height:768});await nav('today');await page.keyboard.press('Tab');const focused=await page.evaluate(()=>{const s=getComputedStyle(document.activeElement);return {outline:s.outlineStyle,width:s.outlineWidth}});assert.notEqual(focused.outline,'none');await click('capture');const cdp=await context.newCDPSession(page),ax=await cdp.send('Accessibility.getFullAXTree');const textboxes=ax.nodes.filter(n=>!n.ignored&&n.role?.value==='textbox');assert.ok(textboxes.length>0&&textboxes.every(n=>n.name?.value));assert.ok(ax.nodes.some(n=>!n.ignored&&n.role?.value==='dialog'&&n.name?.value==='لقطة سريعة'));for(let i=0;i<18;i++){await page.keyboard.press('Tab');assert.ok(await page.evaluate(()=>document.querySelector('#dialog').contains(document.activeElement)))}await page.keyboard.press('Escape');assert.equal(await page.locator('#dialog').evaluate(e=>e.open),false);await nav('search');assert.equal(await page.locator('#f-query').evaluate(e=>e===document.activeElement),true);await nav('today');await page.evaluate(()=>document.documentElement.style.fontSize='34px');await views('text200-desktop',true);await page.setViewportSize({width:390,height:844});await views('text200-mobile',true);await nav('calendar');const labels=await page.locator('.calendar-label').evaluateAll(es=>es.map(e=>({text:e.textContent,width:e.clientWidth,scroll:e.scrollWidth,size:getComputedStyle(e).fontSize})));assert.ok(labels.every(e=>e.scroll<=e.width),JSON.stringify(labels));const geometry=await page.evaluate(()=>{const nav=document.querySelector('.mobile-nav').getBoundingClientRect(),capture=document.querySelector('.float-capture').getBoundingClientRect();return {navTop:nav.top,captureBottom:capture.bottom}});assert.ok(geometry.captureBottom<=geometry.navTop,'Quick Capture must clear resized navigation at 200%');await page.evaluate(()=>document.documentElement.style.fontSize='17px');await page.setViewportSize({width:683,height:384});await views('zoom200-layout',false);await page.emulateMedia({reducedMotion:'reduce'});await click('capture');assert.equal(await page.locator('#dialog').evaluate(e=>getComputedStyle(e).animationName),'none');await click('close-dialog');checks.push({accessibilityTreeNamedTextboxes:textboxes.length,modalTabLoops:18,textSize:'200% CSS root sizing',zoom:'200% equivalent CSS viewport',spokenScreenReader:'requires real assistive technology session'});
 }
 if(phase==='performance'){
  await nav('today');const resources=await page.evaluate(()=>performance.getEntriesByType('resource').filter(r=>r.name.endsWith('.woff2')).map(r=>({file:r.name.split('/').at(-1),bytes:r.decodedBodySize,duration:r.duration})));const optional=['readex','tajawal','almarai','cairo','arabic'];assert.ok(resources.every(r=>!optional.some(f=>r.file.startsWith(f))),'Optional UI font was eagerly rendered before visiting settings');assert.ok(resources.some(r=>r.file==='alexandria.woff2'));assert.ok(resources.some(r=>r.file==='naskh.woff2'));const navTiming=await page.evaluate(()=>{const n=performance.getEntriesByType('navigation')[0];return {domContentLoaded:n.domContentLoadedEventEnd,load:n.loadEventEnd}});checks.push({initialFontResources:resources,navigationMilliseconds:navTiming});const {readdir,stat}=await import('node:fs/promises');const fontFiles=(await readdir('dist/fonts')).filter(f=>f.endsWith('.woff2'));let bytes=0;for(const name of fontFiles)bytes+=(await stat('dist/fonts/'+name)).size;assert.ok(bytes<800000);checks.push({woff2Bytes:bytes,requiredSourceTTFOutsideDist:true});
 }
 if(phase==='matrix'){const sizes=[[360,800],[390,844],[430,932],[768,1024],[1024,768],[1280,800],[1366,768],[1440,900],[1920,1080]];for(const [width,height] of sizes){await page.setViewportSize({width,height});for(const theme of ['light','dark']){await mode(theme);await views(`matrix-${width}x${height}-${theme}`,width===768||width===1440)}}}
 assert.deepEqual(errors,[]);assert.deepEqual(failures,[]);await writeFile(`tests/artifacts/identity/final-${phase}.json`,JSON.stringify({phase,checks,errors,failures},null,2));console.log(`PASS ${phase}: ${checks.length} page inspections; readable mobile inputs; RTL; named controls; no overflow/resources/console failures.`);
}finally{await browser.close()}
