import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import(pathToFileURL('C:/Users/QDU/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs'));
const browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:1440,height:900}});const page=await context.newPage();const errors=[],remoteFonts=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.resourceType()==='font'&&!r.url().startsWith('http://127.0.0.1:4174/'))remoteFonts.push(r.url())});const idle=()=>page.waitForFunction(()=>document.querySelector('#app')?.getAttribute('aria-busy')!=='true');
async function settings(){await idle();if(await page.locator('#dialog[open]').count())await page.locator('[data-action=close-dialog]').click();await page.locator('[data-nav=settings]:visible').first().click();await idle();if(await page.locator('.settings-mobile-select').isVisible())await page.locator('.settings-mobile-select').selectOption('writing');else await page.locator('[data-category=writing]').click()}
const results=[];await mkdir('tests/artifacts/identity',{recursive:true});
try{
 await page.goto('http://127.0.0.1:4174');assert.equal(new URL(page.url()).port,'4174');await settings();await page.evaluate(()=>document.fonts.ready);assert.equal(await page.locator('select[data-pref=uiFont]').inputValue(),'alexandria');assert.equal(await page.locator('select[data-pref=readingFont]').inputValue(),'naskh');assert.equal(await page.locator('.font-card').count(),11);
 const fonts=await page.evaluate(async()=>{const {fontNames,interfaceFonts,readingFonts}=await import('./typography.js');return [...new Set([...interfaceFonts,...readingFonts].map(([id])=>id))].map(id=>[id,fontNames[id]])});
 await page.waitForFunction(()=>!!navigator.serviceWorker.controller);await page.evaluate(()=>navigator.serviceWorker.ready);await context.setOffline(true);
 for(const [id,family] of fonts){await page.locator('select[data-pref=uiFont]').selectOption(id==='naskh'?'alexandria':id);await page.locator('select[data-pref=readingFont]').selectOption(id==='almarai'||id==='tajawal'?'naskh':id);await page.reload();await settings();await page.evaluate(()=>document.fonts.ready);const result=await page.evaluate(async({family})=>{await document.fonts.load(`500 18px ${family}`,'تفصيل صغير، ذكرى كبيرة. ١٢٣ 123 Arabic بغداد؟');return {family,loaded:document.fonts.check(`500 18px ${family}`),matching:[...document.fonts].filter(f=>f.family===family).some(f=>f.status==='loaded'),shapeWidths:[400,500,700].map(weight=>{const c=document.createElement('canvas').getContext('2d');c.font=`${weight} 18px ${family}`;return c.measureText('العراق، ١٢٣ — My memories.').width})}},{family});assert.ok(result.loaded&&result.matching);assert.ok(result.shapeWidths.every(w=>w>50));results.push(result)}
 await context.setOffline(false);await page.locator('select[data-pref=uiFont]').selectOption('alexandria');await page.locator('select[data-pref=readingFont]').selectOption('naskh');await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:'tests/artifacts/identity/font-previews-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'tests/artifacts/identity/font-previews-mobile.png',fullPage:true});assert.deepEqual(errors,[]);assert.deepEqual(remoteFonts,[]);await writeFile('tests/artifacts/identity/fonts.json',JSON.stringify({results,errors,remoteFonts},null,2));console.log('PASS seven local Arabic font families, actual loaded faces, Arabic/English/numerals/punctuation weights, independent defaults, live font previews, every selected family reloaded offline, mobile no overflow.');
}finally{await browser.close()}
