import assert from 'node:assert/strict';import {pathToFileURL} from 'node:url';import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=await import(pathToFileURL('C:/Users/QDU/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs'));const browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext({viewport:{width:1440,height:900}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const results=[];await mkdir('tests/artifacts/identity',{recursive:true});
try{await page.goto('http://127.0.0.1:4174');await page.locator('[data-action=close-dialog]').click();await page.locator('[data-nav=settings]:visible').first().click();await page.locator('[data-category=appearance]').click();const ids=await page.evaluate(async()=>{const t=await import('./themes.js');return {light:t.lightThemes,dark:t.darkThemes}});
 for(const [key,list,mode] of [['palette',ids.light,'light'],['darkPalette',ids.dark,'dark']]){
  if(!await page.locator(`[data-theme-key=${key}]`).count())continue;await page.locator('select[data-pref=theme]').selectOption(mode);await page.waitForFunction(mode=>document.documentElement.dataset.theme===mode,mode);
  for(const id of list){await page.locator(`[data-pref=${key}][value=${id}]`).check();await page.waitForFunction(({key,id,mode})=>document.documentElement.dataset.theme===mode&&document.querySelector(`[data-theme-key=${key}][data-theme-preview=${id}]`).classList.contains('selected'),{key,id,mode});await page.evaluate(()=>document.fonts.ready);const colors=await page.evaluate(()=>{const root=document.documentElement;const s=getComputedStyle(root);return Object.fromEntries(['background','surface','journal-canvas','primary','selection','sidebar-background','focus'].map(k=>[k,s.getPropertyValue('--'+k)]))});assert.ok(Object.values(colors).every(Boolean));const mini=await page.locator(`[data-theme-key=${key}][data-theme-preview=${id}]`).evaluate(el=>({selected:el.classList.contains('selected'),preview:getComputedStyle(el).getPropertyValue('--preview-paper')}));assert.ok(mini.selected&&mini.preview);results.push({key,id,mode,colors});await page.locator('#toast').evaluate(e=>e.classList.remove('visible'));await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0)});await page.screenshot({path:`tests/artifacts/identity/theme-${mode}-${id}.png`,fullPage:true})}
 }
 assert.equal(new Set(results.filter(x=>x.mode==='light').map(x=>x.colors['sidebar-background'])).size,5);await page.reload();await page.locator('[data-action=close-dialog]').click();assert.equal(await page.evaluate(()=>document.documentElement.dataset.theme),results.at(-1).mode);await page.locator('[data-nav=settings]:visible').first().click();await page.locator('[data-category=appearance]').click();await page.locator('select[data-pref=theme]').selectOption('light');await page.waitForFunction(()=>document.documentElement.dataset.theme==='light');await page.locator('.custom-builder summary').click();await page.locator('[data-action=use-custom]').click();await page.locator('[data-pref=customAccent]').fill('#ffffff');await page.locator('[data-pref=customAccent]').dispatchEvent('input');await page.waitForFunction(()=>document.documentElement.dataset.customAdjusted==='true');await page.getByText('عدّلنا درجة لون الأفعال',{exact:false}).waitFor();const custom=await page.evaluate(async()=>{const {contrast}=await import('./themes.js');const s=document.documentElement.style;return contrast(s.getPropertyValue('--primary'),s.getPropertyValue('--background'))});assert.ok(custom>=4.5);await page.locator('[data-action=reset-custom]').click();await page.waitForFunction(()=>document.querySelector('[data-pref=customAccent]').value==='#8a593e');assert.deepEqual(errors,[]);await writeFile('tests/artifacts/identity/themes.json',JSON.stringify({results,errors},null,2));console.log(`PASS ${results.length} actual theme selections, full semantic CSS, immediate preview/sidebar changes, current markers and reload mode persistence.`)
}finally{await browser.close()}
