import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
let chromium;try{({chromium}=await import('playwright'))}catch{({chromium}=await import(pathToFileURL('C:/Users/QDU/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs')))}
const browser=await chromium.launch({headless:true,channel:'msedge'});
const context=await browser.newContext({acceptDownloads:true});await context.addInitScript(()=>{globalThis.qaCacheSeed=caches.open('unrelated-test-shell').then(cache=>cache.put('/unrelated-static-placeholder',new Response('synthetic shell')))});const page=await context.newPage();
const errors=[],checks=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
const idle=()=>page.waitForFunction(()=>document.querySelector('#app').getAttribute('aria-busy')!=='true');
const click=async action=>{await idle();await page.locator(`[data-action="${action}"]:visible`).first().click();await idle()};
const nav=async route=>{if(route==='search')return click('search');if(route==='backup'){await nav('settings');await category('data');return click('backup')}await idle();await page.locator(`[data-nav="${route}"]:visible`).first().click();await idle()};
const category=async id=>{if(await page.locator('.settings-mobile-select').isVisible())await page.locator('.settings-mobile-select').selectOption(id);else await page.locator(`[data-category="${id}"]`).click()};
await mkdir('tests/artifacts/product',{recursive:true});
async function verify(label,shot=false){
 await idle();await page.evaluate(()=>document.fonts.ready);
 const result=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,rtl:document.documentElement.dir,missing:[...document.querySelectorAll('button')].filter(b=>b.checkVisibility()&&!b.textContent.trim()&&!b.getAttribute('aria-label')).length,dialog:document.querySelector('#dialog').open?document.querySelector('#dialog').getBoundingClientRect().height:0}));
 assert.ok(result.scroll<=result.width,`${label}: horizontal overflow ${result.scroll}/${result.width}`);assert.equal(result.rtl,'rtl');assert.equal(result.missing,0);if(result.dialog)assert.ok(result.dialog<=await page.evaluate(()=>innerHeight)+1,label+' dialog exceeds viewport');checks.push(label);
 if(shot){await page.locator('#toast').evaluate(e=>e.classList.remove('visible'));await page.screenshot({path:`tests/artifacts/product/${label}.png`,fullPage:!result.dialog})}
}
async function contrast(){return page.evaluate(()=>{
 const rgb=s=>s.match(/[\d.]+/g).slice(0,3).map(Number);
 const lum=c=>c.map(v=>v/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4).reduce((sum,v,i)=>sum+v*[.2126,.7152,.0722][i],0);
 const ratio=(a,b)=>{a=lum(rgb(a));b=lum(rgb(b));return (Math.max(a,b)+.05)/(Math.min(a,b)+.05)};
 const el=document.createElement('div');document.body.append(el);const color=v=>{el.style.color=`var(--${v})`;return getComputedStyle(el).color};
 const ink=ratio(color('ink'),color('paper')),muted=ratio(color('muted'),color('paper')),button=ratio(color('green'),color('on-accent'));el.remove();return {ink,muted,button};
})}
try{
 await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:4174');assert.equal(new URL(page.url()).port,'4174');
 for(let i=0;i<4;i++){await verify(`onboarding-step-${i+1}`,true);if(i<3)await click('onboarding-next')}
 await click('onboarding-prev');await click('onboarding-next');await click('finish-onboarding');
 await page.locator('[name=answer]').fill('كتبت كلمات اختبار فقط، وذهبت إلى الجامعة.');await page.keyboard.press('Control+Enter');await page.waitForFunction(()=>document.querySelector('.flow-progress').textContent.includes('2 من 3'));assert.match(await page.locator('.flow-progress').textContent(),/2 من 3/);
 await page.locator('[name=answer]').fill('ارتياح، وشيء من التعب');await click('end-session');await click('complete');
 // Deterministic QA anchors exist only in this fresh isolated browser context.
 await page.evaluate(async()=>{const {JournalDB,newDay,dateKey,uid,now}=await import('./core.js');const db=await new JournalDB().open();const date=dateKey();const event={id:uid(),kind:'event',date,journalDayId:`day:${date}`,title:'اختبار موقف مسائي',description:'ذهبنا إلى المقهى ثم عدنا',locationName:'مقهى الاختبار',peopleNames:'أحمد',peopleIds:[],tags:['درس'],emotionIds:[],mediaIds:[],approximateStartTime:'18:30',timeConfidence:'approximate',memoryConfidence:'unsure',rawResponses:[]};await db.put(event);const d=await db.get(`day:${date}`);d.eventIds.push(event.id);await db.put(d);const old=newDay((Number(date.slice(0,4))-1)+date.slice(4));old.title='اختبار ذكرى صعبة';old.status='complete';old.difficult=true;old.entryContent='محتوى اختبار قديم';await db.put(old);const recent=newDay('2026-09-20');recent.status='complete';recent.title='اختبار نتيجة بعيدة';recent.entryContent='تفاصيل اختبار '.repeat(50)+' زُرْتُ الجامِعة أمس';await db.put(recent)});
 await nav('today');assert.equal(await page.getByText('اختبار ذكرى صعبة',{exact:true}).count(),0);
 await click('free');await click('back-rebuild');assert.equal(await page.locator('.day-period').count(),6);await page.locator('.day-period').filter({has:page.getByRole('heading',{name:'المساء',exact:true})}).getByText('اختبار موقف مسائي',{exact:true}).waitFor();await verify('signature-timeline',true);
 await nav('calendar');await page.locator('[data-action=calendar-select]').first().click();await idle();await page.locator('[data-action=calendar-select]').first().press('ArrowLeft');await page.waitForFunction(()=>document.querySelector('.calendar-day[aria-pressed=true]').dataset.date==='2026-10-02');assert.equal(await page.locator('.calendar-day[aria-pressed=true]').getAttribute('data-date'),'2026-10-02');await click('calendar-today');
 await nav('search');await page.locator('[name=query]').fill('زرت الجامعة');await page.locator('#search-form button[type=submit]').click();await page.getByText('اختبار نتيجة بعيدة',{exact:true}).waitFor();assert.match(await page.locator('#search-results mark').first().textContent(),/زُرْتُ الجامِعة/);await verify('search-matching-excerpt',true);
 await click('reset-search');await page.locator('[name=query]').fill('المقهى');await page.locator('#search-form button[type=submit]').click();await page.getByText('مطابقة في موقف مسجل',{exact:true}).waitFor();await click('reset-search');await page.locator('[name=query]').fill('مقهى الاختبار');await page.locator('#search-form button[type=submit]').click();await page.locator('#search-results .entry-row').waitFor();
 await nav('today');await click('explore-emotion');assert.equal(await page.locator('.emotion-word:visible').count(),0);await page.locator('[data-action=emotion-family][data-family="ارتياح"]').click();await page.locator('[data-action=choose-emotion]').first().click();await page.locator('[data-emotion-note]').fill('ملاحظة اختبار');await page.locator('[data-emotion-intensity]').fill('4');await verify('emotion-selected-note',true);await click('save-emotions');
 await page.keyboard.press('Control+k');await page.locator('#command-query').fill('التقويم');await page.keyboard.press('ArrowDown');assert.equal(await page.evaluate(()=>document.activeElement.dataset.target),'calendar');await page.keyboard.press('Enter');await page.locator('.calendar').waitFor();
 await nav('today');await click('free');await click('focus-mode');assert.equal(await page.locator('.sidebar').isVisible(),false);await page.keyboard.press('Escape');assert.equal(await page.locator('.sidebar').isVisible(),true);const before=await page.locator('[name=entry]').evaluate(el=>el.getBoundingClientRect().height);await page.locator('[name=entry]').fill('سطور اختبار فقط\n'.repeat(80));await page.waitForFunction(()=>document.querySelector('[name=entry]').getBoundingClientRect().height>1200);assert.ok(await page.locator('[name=entry]').evaluate(el=>el.getBoundingClientRect().height)>before);await page.locator('[name=entry]').fill('كلمات اختبار — Arabic and English.');await idle();
 const routes=['today','journal','calendar','memories','insights','search','backup','settings'];
 for(const theme of ['light','dark']){
  await page.setViewportSize({width:1440,height:1000});await nav('settings');await category('appearance');await page.locator('[data-pref=theme]').selectOption(theme);const ratios=await contrast();for(const [role,ratio]of Object.entries(ratios))assert.ok(ratio>=4.5,`${theme} ${role}: ${ratio}`);
  for(const width of [360,390,430,768,820,1024,1280,1366,1440,1920]){
   await page.setViewportSize({width,height:width<=430?844:1000});
   for(const route of routes){await nav(route);await verify(`${theme}-${width}-${route}`,width===390||width===1440)}
   await nav('today');await click('free');await verify(`${theme}-${width}-editor`,width===390||width===1440);await click('reading');await verify(`${theme}-${width}-reading`,width===390||width===1440);await click('free');await click('back-rebuild');await verify(`${theme}-${width}-rebuild`,width===390||width===1440);
   await nav('today');await click('start-mode');await verify(`${theme}-${width}-guided`,width===390||width===1440);await nav('today');await click('capture');await verify(`${theme}-${width}-capture`,width===390||width===1440);
   for(let i=0;i<12;i++){await page.keyboard.press('Tab');assert.equal(await page.evaluate(()=>document.querySelector('#dialog').contains(document.activeElement)),true,`${theme}-${width} focus trap tab ${i}`)}await click('close-dialog');await click('explore-emotion');await verify(`${theme}-${width}-emotion-families`,width===390||width===1440);await page.locator('[data-action=emotion-family]').first().click();await verify(`${theme}-${width}-emotion-words`,width===390||width===1440);await click('uncertain-emotion');await verify(`${theme}-${width}-uncertain`,width===390||width===1440);await click('close-dialog');
  }
  await page.setViewportSize({width:1440,height:1000});await nav('settings');for(const id of ['appearance','writing','layout','today','accessibility','reminders','memories','privacy','data','offline','assistant']){await category(id);assert.equal(await page.locator('.settings-panel:visible').count(),1);await verify(`${theme}-settings-${id}`,true)}
  await nav('memories');for(const action of ['people','places','words','letters','snapshots','exercises']){await click(action);await verify(`${theme}-secondary-${action}`,true);await nav('memories')}
  await nav('insights');await click('reviews');await verify(`${theme}-weekly-review`,true);await click('monthly-review');await page.getByRole('heading',{name:'شهر من حياتي',exact:true}).waitFor();await verify(`${theme}-monthly-review`,true);
 }
 await page.setViewportSize({width:1440,height:1000});await nav('today');await click('free');await click('reading');await page.emulateMedia({media:'print'});assert.equal(await page.locator('.sidebar').isVisible(),false);assert.equal(await page.locator('.reading').isVisible(),true);await page.pdf({path:'tests/artifacts/product/reading.pdf',format:'A4',printBackground:true});await page.emulateMedia({media:'screen'});checks.push('print-reading-pdf');
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.documentElement.style.setProperty('--font-size','34px'));for(const route of routes){await nav(route);await verify(`text200-${route}`,true)}await nav('today');await click('free');await verify('text200-editor',true);await page.evaluate(()=>document.documentElement.style.setProperty('--font-size','17px'));
 await page.emulateMedia({reducedMotion:'reduce'});await nav('today');await click('capture');assert.equal(await page.locator('[name=capture-content]').evaluate(el=>getComputedStyle(el).transitionDuration),'0s');await page.setViewportSize({width:390,height:420});await page.locator('[name=capture-content]').fill('اختبار مساحة لوحة المفاتيح');await verify('keyboard-height-capture',true);await click('save-capture');await click('free');await page.locator('[name=entry]').focus();await verify('keyboard-height-editor',true);
 await page.setViewportSize({width:390,height:844});await nav('settings');await category('offline');assert.match(await page.locator('#offline-status').textContent(),/جاهز/);await page.waitForFunction(()=>navigator.serviceWorker.controller);assert.ok(await page.evaluate(async()=>{await globalThis.qaCacheSeed;return (await caches.keys()).includes('unrelated-test-shell')}));await context.setOffline(true);await page.reload();await page.locator('.shell').waitFor();await nav('today');await click('free');await page.evaluate(()=>document.fonts.ready);assert.ok(await page.evaluate(()=>document.fonts.check('400 17px AlexandriaArabic')));await verify('offline-editor',true);await context.setOffline(false);
 assert.deepEqual(errors,[]);await writeFile('tests/artifacts/product/results.json',JSON.stringify({passed:true,checks,errors,isolatedOrigin:'http://127.0.0.1:4174',actualHardwareKeyboardTest:false},null,2));console.log(`PASS ${checks.length} product checks: settings sections, signature timeline, calendar keyboard, actual excerpts, command palette, focus mode, growing editor, labels, dialog focus trap, contrast, 200% text, reduced motion and offline fonts.`);
}finally{await browser.close()}
