import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
const {chromium}=await import(pathToFileURL('C:/Users/QDU/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs'));

async function setting(key){const map={readingFont:'writing',uiFont:'writing',fontWeight:'writing',readingWidth:'writing',readingLineHeight:'writing',density:'layout',corners:'layout',sidebarTone:'layout',sidebarSide:'layout',navigationStyle:'layout',defaultMode:'layout',showWeek:'today',showOnThisDay:'today',showEmotionHelper:'today',showDailyModes:'today',reduceMotion:'accessibility'};const category=map[key]||(['data','privacy','accessibility'].includes(key)?key:'appearance');const select=page.locator('.settings-mobile-select');if(await select.isVisible())await select.selectOption(category);else await page.locator(`[data-category="${category}"]`).click()}
const browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const idle=()=>page.waitForFunction(()=>document.querySelector('#app').getAttribute('aria-busy')!=='true');
const click=async action=>{await idle();await page.locator(`[data-action="${action}"]:visible`).first().click();await idle()};
const nav=async route=>{await idle();await page.locator(`[data-nav="${route}"]:visible`).first().click();await idle()};
await mkdir('tests/artifacts/renewal',{recursive:true});
const shot=async name=>{await page.evaluate(()=>document.fonts.ready);await page.locator('#toast').evaluate(e=>e.classList.remove('visible'));await page.screenshot({path:`tests/artifacts/renewal/${name}.png`,fullPage:true})};
const pref=async (key,value,prop,expected)=>{await setting(key);await setting(key);await page.locator(`select[data-pref="${key}"]`).selectOption(value);await page.waitForFunction(([prop,expected])=>document.documentElement.style.getPropertyValue(prop)===expected,[prop,expected])};
try{
 await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:4174');await page.locator('[data-action=finish-onboarding]').waitFor();await click('close-dialog');await shot('today-desktop');assert.ok(await page.evaluate(()=>document.fonts.check('400 17px AlexandriaArabic')));await page.setViewportSize({width:390,height:844});await shot('today-mobile');await page.setViewportSize({width:1440,height:1000});await nav('settings');await shot('settings-desktop');await page.setViewportSize({width:390,height:844});await shot('settings-mobile');await page.setViewportSize({width:1440,height:1000});await nav('today');await click('capture');await page.locator('[name=capture-content]').fill('اختبار تخصيص معزول');await click('save-capture');
 await nav('settings');await pref('readingFont','naskh','--reading-font','NaskhArabic');await pref('uiFont','plex','--ui-font','JournalArabic');await pref('fontWeight','600','--ui-weight','600');
 for(const [key,value,attribute] of [['density','compact','density'],['corners','crisp','corners'],['sidebarTone','light','sidebarTone'],['sidebarSide','left','sidebarSide'],['navigationStyle','icons','navigationStyle']]){await setting(key);await page.locator(`select[data-pref="${key}"]`).selectOption(value);await page.waitForFunction(([key,value])=>document.documentElement.dataset[key]===value,[attribute,value])}
 await setting('palette');await page.locator('[data-pref=palette][value=ink]').check();await page.waitForFunction(()=>document.documentElement.style.getPropertyValue('--green')==='#405d83');await setting('showWeek');await page.locator('[data-pref=showWeek]').uncheck();await page.waitForFunction(()=>document.documentElement.dataset.showWeek==='false');await nav('today');assert.equal(await page.locator('.week-panel:visible').count(),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 await page.reload();await page.locator('[data-action=finish-onboarding]').waitFor();await click('close-dialog');assert.equal(await page.evaluate(()=>document.documentElement.dataset.navigationStyle),'icons');assert.equal(await page.evaluate(()=>document.documentElement.dataset.sidebarSide),'left');assert.equal(await page.evaluate(()=>document.documentElement.style.getPropertyValue('--reading-font')),'NaskhArabic');await page.getByText('اختبار تخصيص معزول',{exact:true}).waitFor();await nav('settings');await setting('accessibility');await click('reset-appearance');assert.equal(await page.evaluate(()=>document.documentElement.style.getPropertyValue('--green')),'#865438');assert.equal(await page.evaluate(()=>document.documentElement.dataset.sidebarSide),'right');await nav('today');await page.getByText('اختبار تخصيص معزول',{exact:true}).waitFor();
 await nav('settings');await setting('palette');await page.locator('.custom-builder summary').click();await click('use-custom');await page.waitForFunction(()=>document.documentElement.dataset.palette==='custom');await page.locator('[data-pref=customAccent]').fill('#50382a');await page.locator('[data-pref=customAccent]').dispatchEvent('change');await page.waitForFunction(()=>document.documentElement.style.getPropertyValue('--green')==='#50382a');await pref('uiFont','cairo','--ui-font','CairoArabic');await page.waitForFunction(()=>navigator.serviceWorker.controller);await context.setOffline(true);await page.reload();await page.locator('[data-action=finish-onboarding]').waitFor();await click('close-dialog');await page.evaluate(()=>document.fonts.ready);assert.ok(await page.evaluate(()=>document.fonts.check('500 17px CairoArabic')));assert.equal(await page.evaluate(()=>document.documentElement.style.getPropertyValue('--green')),'#50382a');await context.setOffline(false);
 const restored=await page.evaluate(async()=>{const {JournalDB}=await import('./core.js');const db=await new JournalDB('qadawi-appearance-roundtrip').open();const source=new JournalDB();await source.open();const backup=await source.backup();await db.restore(backup);const settings=await db.get('settings:main');return {font:settings.uiFont,accent:settings.customAccent,records:await db.count('capture')}});assert.equal(restored.font,'cairo');assert.equal(restored.accent,'#50382a');assert.equal(restored.records,1);
 await nav('calendar');const initialMonth=await page.locator('[name=month]').inputValue();await click('month-next');assert.notEqual(await page.locator('[name=month]').inputValue(),initialMonth);assert.equal(await page.locator('[data-action=month-next] svg').getAttribute('data-icon'),'chevron');assert.ok(await page.locator('[data-action=month-next]').getAttribute('aria-label'));await click('month-prev');assert.equal(await page.locator('[name=month]').inputValue(),initialMonth);
 await page.evaluate(async()=>{const {applyAppearance}=await import('./appearance.js');applyAppearance({palette:'constructor',uiFont:'__proto__',readingFont:'prototype',readingWidth:'constructor',readingLineHeight:'bad'});if(document.documentElement.style.getPropertyValue('--green')!=='#865438'||document.documentElement.style.getPropertyValue('--reading-font')!=='CairoArabic')throw Error('Unsafe appearance import fallback')});
 assert.deepEqual(errors,[]);await writeFile('tests/artifacts/renewal/results.json',JSON.stringify({passed:true,persistence:true,customization:true,offlineFonts:true,backupRoundtrip:true,errors},null,2));console.log('PASS appearance customization, persistence, layouts, reset preserves content, custom color, local offline fonts and JSON backup roundtrip');
}finally{await browser.close()}
