import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
let chromium;try{({chromium}=await import('playwright'))}catch{({chromium}=await import(pathToFileURL('C:/Users/QDU/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs')))}
const browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
const idle=()=>page.waitForFunction(()=>document.querySelector('#app').getAttribute('aria-busy')!=='true');
const click=async action=>{await idle();await page.locator(`[data-action="${action}"]:visible`).first().click();await idle()};
try{
 await page.goto('http://127.0.0.1:4174');assert.equal(new URL(page.url()).port,'4174');await click('finish-onboarding');await page.locator('[name=answer]').fill('اختبار مراجعات فقط');await click('end-session');await click('complete');
 const original=await page.evaluate(async()=>{const {JournalDB,newDay,uid,dateKey,now}=await import('./core.js');const db=await new JournalDB().open();const day=newDay('2026-09-03');day.status='complete';day.title='صفحة سبتمبر الاختبارية';day.entryContent='تفصيل محفوظ لاختبار الطباعة. Arabic and English.';const old={...day,entryContent:'النص الأصلي قبل الاستيراد'};await db.batch([day,{id:uid(),kind:'revision',date:dateKey(),targetId:day.id,record:old,createdAt:now(),reason:'قبل الاستيراد'}]);return JSON.stringify(day)});
 await page.locator('[data-nav=journal]').first().click();await idle();await page.locator('[data-action=open-day][data-date="2026-09-03"]').click();await idle();await click('history');await page.getByText('النص الأصلي قبل الاستيراد',{exact:true}).waitFor();await click('close-dialog');
 await page.emulateMedia({media:'print'});assert.equal(await page.locator('.sidebar').isVisible(),false);assert.equal(await page.locator('.no-print:visible').count(),0);await page.getByText('تفصيل محفوظ لاختبار الطباعة. Arabic and English.',{exact:true}).waitFor();const pdf=await page.pdf({path:'tests/artifacts/product/reading.pdf',format:'A4',printBackground:true});assert.equal(pdf.subarray(0,4).toString(),'%PDF');assert.ok(pdf.length>10000);await page.emulateMedia({media:'screen'});
 await page.locator('[data-nav=calendar]').first().click();await idle();await page.locator('[data-month-picker]').fill('2026-09');await page.locator('[data-month-picker]').dispatchEvent('change');await page.locator('[data-action=calendar-select][data-date="2026-09-03"]').click();await idle();await click('weekly-review');await page.getByRole('heading',{name:'أسبوع من حياتي',exact:true}).waitFor();assert.equal(await page.locator('[name=review-reflection]').getAttribute('data-review-id'),'review:week:2026-08-28');
 await click('monthly-review');await page.getByRole('heading',{name:'شهر من حياتي',exact:true}).waitFor();assert.equal(await page.locator('[name=review-reflection]').getAttribute('data-review-id'),'review:month:2026-09-01');await page.locator('[name=review-reflection]').fill('فقرة شهر سبتمبر الاختبارية');await page.waitForFunction(()=>document.querySelector('#save-state').textContent==='محفوظ على جهازك');
 await page.evaluate(async text=>{const {JournalDB}=await import('./core.js');const db=await new JournalDB().open();if(JSON.stringify(await db.get('day:2026-09-03'))!==text)throw Error('Review navigation altered the old day');const review=await db.get('review:month:2026-09-01');if(review.periodType!=='month'||review.userReflection!=='فقرة شهر سبتمبر الاختبارية')throw Error('Monthly review was not saved')},original);
 await page.evaluate(()=>{document.activeElement?.blur();window.scrollTo(0,0)});await page.waitForTimeout(150);assert.ok(Math.abs((await page.locator('.sidebar').boundingBox()).y)<2);await page.screenshot({path:'tests/artifacts/product/verified-monthly-review.png',fullPage:true});assert.deepEqual(errors,[]);console.log('PASS actual weekly/monthly periods, monthly reflection autosave, historical import revision visibility, unchanged original day, print-only reading and generated PDF.');
}finally{await browser.close()}
