import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
import {pathToFileURL} from 'node:url';
let chromium;try{({chromium}=await import('playwright'))}catch{({chromium}=await import(pathToFileURL('C:/Users/QDU/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs')))}
const browser=await chromium.launch({headless:true,channel:'msedge'});const context=await browser.newContext();const page=await context.newPage();const idle=()=>page.waitForFunction(()=>document.querySelector('#app').getAttribute('aria-busy')!=='true');const errors=[];page.on('pageerror',e=>errors.push(e.message));
try{
 await page.goto('http://127.0.0.1:4174');assert.equal(new URL(page.url()).port,'4174');await page.locator('[data-action=close-dialog]').click();
 const seeded=await page.evaluate(async()=>{const {JournalDB,newDay,uid}=await import('./core.js');const db=await new JournalDB().open();const start=performance.now(),records=[];for(let i=0;i<3000;i++){const time=new Date(Date.UTC(2016,0,1+i)),date=time.toISOString().slice(0,10),d=newDay(date);d.status='complete';d.title='صفحة اختبار '+i;d.entryContent='كلمات اصطناعية لاختبار الحجم فقط. '.repeat(12)+(i===2450?'تفصيل الاسترجاع':'');records.push(d,{id:uid(),kind:'event',date,journalDayId:d.id,title:'موقف اختبار',description:'موقف اصطناعي لاختبار البحث',peopleIds:[],peopleNames:'أحمد الاختبار',locationName:'مكان الاختبار',emotionIds:[],mediaIds:[],tags:[],rawResponses:[]})}await db.batch(records);return {days:await db.count('day'),events:await db.count('event'),seedMs:Math.round(performance.now()-start)}});
 let start=Date.now();await page.locator('[data-nav=journal]').first().click();await idle();await page.locator('.entry-row').first().waitFor();assert.equal(await page.locator('.entry-row').count(),20);const archiveMs=Date.now()-start;await page.locator('[data-action=page-next]').click();await idle();await page.waitForFunction(()=>document.querySelector('.entry-preview h2')?.textContent==='صفحة اختبار 2979');
 await page.locator('[data-action=search]').click();await idle();await page.locator('[name=query]').fill('تفصيل الاسترجاع');start=Date.now();await page.locator('#search-form button[type=submit]').click();await idle();await page.waitForFunction(()=>document.querySelector('#search-results')?.textContent.includes('1 نتيجة'));const searchMs=Date.now()-start;await page.getByRole('heading',{name:'صفحة اختبار 2450',exact:true}).waitFor();assert.equal(await page.locator('#search-results .entry-row').count(),1);
 await page.locator('[name=query]').fill('كلمات اصطناعية');await page.locator('#search-form button[type=submit]').click();await idle();await page.waitForFunction(()=>document.querySelector('#search-results')?.textContent.includes('3000 نتيجة'));assert.equal(await page.locator('#search-results .entry-row').count(),20);await page.locator('[data-action=search-more]').click();await idle();await page.waitForFunction(()=>document.querySelector('#search-results .entry-preview h2')?.textContent==='صفحة اختبار 2979');assert.equal(await page.locator('#search-results .entry-row').count(),20);
 assert.deepEqual(errors,[]);const result={...seeded,archiveMs,searchMs,renderedArchive:20,renderedSearch:20,errors,mediaScaleNotBenchmarked:true};await writeFile('tests/artifacts/scale-results.json',JSON.stringify(result,null,2));console.log('PASS isolated 3,000-day + 3,000-event retrieval and pagination',result);
}finally{await browser.close()}
